<?php 
include "db_connect.php"; 
$NO_KK = $_POST['NO_KK'];
$NAMA_KK = $_POST['NAMA_KK']; 
$NAMA_ANGGOTA = $_POST['NAMA_ANGGOTA']; 
$NIK = $_POST['NIK']; 
$TGL_LAHIR = $_POST['TGL_LAHIR']; 
$JENIS_KELAMIN = $_POST['JENIS_KELAMIN']; 
$GOL_DARAH = $_POST['GOL_DARAH']; 
$AGAMA = $_POST['AGAMA']; 
$PEND_TERAKHIR = $_POST['PEND_TERAKHIR']; 
$PEKERJAAN = $_POST['PEKERJAAN']; 
$STATUS_KAWIN = $_POST['STATUS_KAWIN']; 
$STATUS_HUB_KEL = $_POST['STATUS_HUB_KEL']; 
$KEWARGANEGARAAN = $_POST['KEWARGANEGARAAN']; 
$NAMA_AYAH= $_POST['NAMA_AYAH']; 
$NAMA_IBU = $_POST['NAMA_IBU']; 
$RT= $_POST['RT']; 
$RW= $_POST['RW']; 

$query1=mysqli_query($kon, "INSERT IGNORE INTO KK_MAIN(NO_KK, NAMA_KK, RT, RW) VALUES ('$NO_KK', '$NAMA_KK','$RT', '$RW')") or die (mysqli_error());
if ($GOL_DARAH==='NULL') {
   $query2=mysqli_query($kon, "INSERT IGNORE INTO KK_KEL(NO_KK, NAMA_ANGGOTA, NIK, TGL_LAHIR, JENIS_KELAMIN, GOL_DARAH, AGAMA, PEND_TERAKHIR, PEKERJAAN, STATUS_KAWIN, STATUS_HUB_KEL, KEWARGANEGARAAN, NAMA_AYAH, NAMA_IBU) VALUES ('$NO_KK', '$NAMA_ANGGOTA', '$NIK', '$TGL_LAHIR', '$JENIS_KELAMIN', NULL, '$AGAMA', '$PEND_TERAKHIR', '$PEKERJAAN', '$STATUS_KAWIN', '$STATUS_HUB_KEL', '$KEWARGANEGARAAN', '$NAMA_AYAH','$NAMA_IBU')") or die (mysqli_error()); 
} else {
   $query2=mysqli_query($kon, "INSERT IGNORE INTO KK_KEL(NO_KK, NAMA_ANGGOTA, NIK, TGL_LAHIR, JENIS_KELAMIN, GOL_DARAH, AGAMA, PEND_TERAKHIR, PEKERJAAN, STATUS_KAWIN, STATUS_HUB_KEL, KEWARGANEGARAAN, NAMA_AYAH, NAMA_IBU) VALUES ('$NO_KK', '$NAMA_ANGGOTA', '$NIK', '$TGL_LAHIR', '$JENIS_KELAMIN', '$GOL_DARAH', '$AGAMA', '$PEND_TERAKHIR', '$PEKERJAAN', '$STATUS_KAWIN', '$STATUS_HUB_KEL', '$KEWARGANEGARAAN', '$NAMA_AYAH','$NAMA_IBU')") or die (mysqli_error()); 
}

 
if($query1 AND $query2) {
?>
<script language="JavaScript">
   document.location='tables.php'</script> 
<?php 
} 
?>
