<?php 
include "db_connect.php"; 
$NIK = $_GET['NIK']; 
 
$NO_KK = $_POST['NO_KK'];
$NAMA_KK = $_POST['NAMA_KK']; 
$NAMA_ANGGOTA = $_POST['NAMA_ANGGOTA']; 
$NIK = $_POST['NIK']; 
$TGL_LAHIR = $_POST['TGL_LAHIR']; 
$JENIS_KELAMIN = $_POST['JENIS_KELAMIN']; 
$GOL_DARAH = $_POST['GOL_DARAH']; 
$AGAMA = $_POST['AGAMA']; 
$PEND_TERAKHIR = $_POST['PEND_TERAKHIR']; 
$PEKERJAAN = $_POST['PEKERJAAN']; 
$STATUS_KAWIN = $_POST['STATUS_KAWIN']; 
$STATUS_HUB_KEL = $_POST['STATUS_HUB_KEL']; 
$KEWARGANEGARAAN = $_POST['KEWARGANEGARAAN']; 
$NAMA_AYAH= $_POST['NAMA_AYAH']; 
$NAMA_IBU = $_POST['NAMA_IBU']; 

if ($GOL_DARAH==='NULL') {
   $query=mysqli_query($kon, "UPDATE KK_KEL SET NAMA_ANGGOTA='$NAMA_ANGGOTA', NIK='$NIK', TGL_LAHIR='$TGL_LAHIR', JENIS_KELAMIN='$JENIS_KELAMIN', GOL_DARAH=$GOL_DARAH, AGAMA='$AGAMA', PEND_TERAKHIR='$PEND_TERAKHIR', PEKERJAAN='$PEKERJAAN', STATUS_KAWIN='$STATUS_KAWIN', STATUS_HUB_KEL='$STATUS_HUB_KEL', KEWARGANEGARAAN='$KEWARGANEGARAAN', NAMA_AYAH='$NAMA_AYAH', NAMA_IBU='$NAMA_IBU' WHERE NIK='$NIK'") or die (mysqli_error());
} else {
   $query=mysqli_query($kon, "UPDATE KK_KEL SET NAMA_ANGGOTA='$NAMA_ANGGOTA', NIK='$NIK', TGL_LAHIR='$TGL_LAHIR', JENIS_KELAMIN='$JENIS_KELAMIN', AGAMA='$AGAMA', PEND_TERAKHIR='$PEND_TERAKHIR', PEKERJAAN='$PEKERJAAN', STATUS_KAWIN='$STATUS_KAWIN', STATUS_HUB_KEL='$STATUS_HUB_KEL', KEWARGANEGARAAN='$KEWARGANEGARAAN', NAMA_AYAH='$NAMA_AYAH', NAMA_IBU='$NAMA_IBU' WHERE NIK='$NIK'") or die (mysqli_error());
}



if($query) {
?>
<script language="JavaScript">
   document.location='tables.php'</script> 
<?php 
} 
?>



